DATA:
  NAME: "CUB"
  DATAPATH: "src/data/CUB_200_2011"  #TODO: need to specify here
  NUMBER_CLASSES: 200
  MULTILABEL: False
  CLASSESPATH: "src/data/CUB_200_2011/labels.txt"
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 4
  WARMUP_EPOCH: 0