DATA:
  NAME: "vtab-patch_camelyon"
  DATAPATH: ""
  NUMBER_CLASSES: 2
  MULTILABEL: False
  CLASSESPATH: "src/data/caltech101/3.0.1/label.labels.txt"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 100
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 5
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9
