DATA:
  NAME: "vtab-patch_camelyon"
  DATAPATH: ""
  NUMBER_CLASSES: 2
  MULTILABEL: False
  CLASSESPATH: "src/data/patch_camelyon/2.0.0/classes.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 5
SOLVER:
  BASE_LR: 1.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 5
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9