DATA:
  NAME: 'vtab-smallnorb(predicted_attribute="label_azimuth")'
  NUMBER_CLASSES: 18
  MULTILABEL: False
  CLASSESPATH: "src/data/datasets/prompts/smallnorb/azimuth.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 100
SOLVER:
  BASE_LR: 50.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 50
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9