DATA:
  NAME: "vtab-svhn_cropped"
  DATAPATH: ""
  NUMBER_CLASSES: 10
  MULTILABEL: False
  CLASSESPATH: "src/data/svhn_cropped/3.0.0/classes.txt"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 50
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 5
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9