DATA:
  NAME: "vtab-caltech101"
  DATAPATH: ""
  NUMBER_CLASSES: 102
  MULTILABEL: False
  CLASSESPATH: "src/data/caltech101/3.0.1/label.labels.txt"
MODEL:
  TYPE: "CLIP-VPT"
  BACKBONE: "ViT-B32"
  PROMPT:
    NUM_TOKENS: 10
SOLVER:
  BASE_LR: 1.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 3
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9
