DATA:
  NAME: 'vtab-smallnorb(predicted_attribute="label_azimuth")'
  NUMBER_CLASSES: 18
  MULTILABEL: False
  CLASSESPATH: "src/data/svhn_cropped/3.0.0/classes.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 100
SOLVER:
  BASE_LR: 1.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 10
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9