DATA:
  NAME: "vtab-sun397"
  DATAPATH: ""
  NUMBER_CLASSES: 397
  MULTILABEL: False
  CLASSESPATH: "src/data/datasets/prompts/sun397/classes.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 50
SOLVER:
  BASE_LR: 1.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 5
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9