DATA:
  NAME: "vtab-svhn"
  DATAPATH: ""
  NUMBER_CLASSES: 10
  MULTILABEL: False
  CLASSESPATH: "src/data/svhn_cropped/3.0.0/classes.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 50
SOLVER:
  BASE_LR: 1.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 40
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9