DATA:
  NAME: "vtab-eurosat"
  DATAPATH: ""
  NUMBER_CLASSES: 10
  MULTILABEL: False
  CLASSESPATH: "src/data/eurosat/rgb/2.0.0/label.labels.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "CLIP-Adapter"
  PROMPT:
    NUM_TOKENS: 100
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 30
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9
