DATA:
  NAME: "vtab-oxford_flowers102"
  DATAPATH: ""
  NUMBER_CLASSES: 102
  MULTILABEL: False
  CLASSESPATH: "src/data/caltech101/3.0.1/label.labels.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "CLIP-Adapter"
  BACKBONE: "ViT-B32"
  PROMPT:
    NUM_TOKENS: 10
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.00001
  TOTAL_EPOCH: 2
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9