DATA:
  NAME: "StanfordCars"
  DATAPATH: "src/data/stanfordcars"  #TODO: need to specify here
  NUMBER_CLASSES: 196
  MULTILABEL: False
  CLASSESPATH: "src/data/stanfordcars/meta/labels.txt"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 100
SOLVER:
  BASE_LR: 10.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 30
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9
