DATA:
  NAME: 'vtab-clevr(task="count_all")'
  NUMBER_CLASSES: 8
  MULTILABEL: False
  CLASSESPATH: "src/data/svhn_cropped/3.0.0/classes.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 50
SOLVER:
  BASE_LR: 10.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 5
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9