DATA:
  NAME: 'vtab-diabetic_retinopathy(config="btgraham-300")'
  NUMBER_CLASSES: 300
  MULTILABEL: False
  CLASSESPATH: "src/data/datasets/prompts/smallnorb/azimuth.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 100
SOLVER:
  BASE_LR: 50.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 50
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9