DATA:
  NAME: 'vtab-dmlab'
  NUMBER_CLASSES: 6
  MULTILABEL: False
  CLASSESPATH: "src/data/dmlab/2.0.1/classes.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 200
SOLVER:
  BASE_LR: 5.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 10
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9