DATA:
  NAME: "StanfordDogs"
  DATAPATH: "src/data/stanford-dogs"  #TODO: need to specify here
  NUMBER_CLASSES: 120
  MULTILABEL: False
  CLASSESPATH: "src/data/stanford-dogs/labels.txt"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 200
SOLVER:
  BASE_LR: 10.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 5
  WARMUP_EPOCH: 0