DATA:
  NAME: "vtab-oxford_flowers102"
  DATAPATH: "src/data/oxford-flowers"  #TODO: need to specify here
  NUMBER_CLASSES: 102
  MULTILABEL: False
  CLASSESPATH: "src/data/oxford_flowers102/2.1.1/label.labels.txt"
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 1.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 10
  WARMUP_EPOCH: 5