DATA:
  NAME: 'vtab-kitti(task="closest_vehicle_distance")'
  NUMBER_CLASSES: 4
  MULTILABEL: False
  CLASSESPATH: "src/data/kitti/3.3.0/classes.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 100
SOLVER:
  BASE_LR: 10.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 10
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9