DATA:
  NAME: 'vtab-resisc45'
  NUMBER_CLASSES: 45
  MULTILABEL: False
  CLASSESPATH: "src/data/datasets/prompts/resisc45/classes.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 100
SOLVER:
  BASE_LR: 10.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 20
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9