DATA:
  NAME: 'vtab-smallnorb(predicted_attribute="label_elevation")'
  NUMBER_CLASSES: 9
  MULTILABEL: False
  CLASSESPATH: "src/data/datasets/prompts/smallnorb/elevation.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 200
SOLVER:
  BASE_LR: 10.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 10
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9