DATA:
  NAME: "vtab-svhn"
  DATAPATH: ""
  NUMBER_CLASSES: 10
  MULTILABEL: False
  CLASSESPATH: "src/data/sun397/tfds/4.0.0/label.labels.txt"
  DATAPATH: "src/data/"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 200
SOLVER:
  BASE_LR: 80.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 5
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9