DATA:
  NAME: "StanfordCars"
  DATAPATH: "src/data/stanfordcars"  #TODO: need to specify here
  NUMBER_CLASSES: 196
  MULTILABEL: False
  CLASSESPATH: "src/data/stanfordcars/meta/labels.txt"
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.3
  WEIGHT_DECAY: 0.01
