DATA:
  NAME: "vtab-dtd"
  DATAPATH: ""
  NUMBER_CLASSES: 47
  MULTILABEL: False
  CLASSESPATH: "src/data/dtd/3.0.1/label.labels.txt"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 100
SOLVER:
  BASE_LR: 10.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 30
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9
