DATA:
  NAME: "OxfordFlowers"
  DATAPATH: "src/data/oxford-flowers"  #TODO: need to specify here
  NUMBER_CLASSES: 102
  MULTILABEL: False
  CLASSESPATH: "src/data/oxford-flowers/labels.txt"
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 10
  WARMUP_EPOCH: 0