DATA:
  NAME: "food-101"
  DATAPATH: "src/data/food-101"  #TODO: need to specify here
  NUMBER_CLASSES: 101
  MULTILABEL: False
  CLASSESPATH: "src/data/food-101/meta/labels.txt"
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TOTAL_EPOCH: 5
  WARMUP_EPOCH: 0