DATA:
  NAME: "vtab-oxford_iiit_pet"
  DATAPATH: ""
  NUMBER_CLASSES: 2
  MULTILABEL: False
  CLASSESPATH: "src/data/oxford_iiit_pet/3.2.0/species.labels.txt"
MODEL:
  TYPE: "vit"
  PROMPT:
    NUM_TOKENS: 100
SOLVER:
  BASE_LR: 10.0
  WEIGHT_DECAY: 0.0001
  TOTAL_EPOCH: 30
  WARMUP_EPOCH: 5
  MOMENTUM: 0.9
